export const TASKS_LIST_REQUEST = "TASKS_LIST_REQUEST";
export const TASKS_LIST_SUCCESS = "TASKS_LIST_SUCCESS";
export const TASKS_LIST_FAIL = "TASKS_LIST_FAIL";

export const TASKS_GET_REQUEST = "TASKS_GET_REQUEST";
export const TASKS_GET_SUCCESS = "TASKS_GET_SUCCESS";
export const TASKS_GET_FAIL = "TASKS_GET_FAIL";

export const TASKS_ADD_REQUEST = "TASKS_ADD_REQUEST";
export const TASKS_ADD_SUCCESS = "TASKS_ADD_SUCCESS";
export const TASKS_ADD_FAIL = "TASKS_ADD_FAIL";

export const TASKS_UPDATE_REQUEST = "TASKS_UPDATE_REQUEST";
export const TASKS_UPDATE_SUCCESS = "TASKS_UPDATE_SUCCESS";
export const TASKS_UPDATE_FAIL = "TASKS_UPDATE_FAIL";
export const TASKS_UPDATE_RESET = "TASKS_UPDATE_RESET";

export const TASKS_DELETE_REQUEST = "TASKS_DELETE_REQUEST";
export const TASKS_DELETE_SUCCESS = "TASKS_DELETE_SUCCESS";
export const TASKS_DELETE_FAIL = "TASKS_DELETE_FAIL";

export const TASKS_REMINDER_TOGGLE_REQUEST = "TASKS_REMINDER_TOGGLE_REQUEST";
export const TASKS_REMINDER_TOGGLE_SUCCESS = "TASKS_REMINDER_TOGGLE_SUCCESS";
export const TASKS_REMINDER_TOGGLE_FAIL = "TASKS_REMINDER_TOGGLE_FAIL";
